version: '3'
services:
    countly:
        image: countly/countly-server
        restart: always
        ports:
            - ${COUNTLY_PORT}:80
        volumes:
            - countly-db:/var/lib/mongodb
volumes:
  countly-db:
